export const FETCH_PRODUCT='FETCH_PRODUCT';
export const ADD_WISHLIST='ADD_WISHLIST';
export const FETCH_WISHLIST='FETCH_WISHLIST';
export const REMOVE_WISHLIST='REMOVE_WISHLIST';
export const REMOVE_PRODUCT='REMOVE_PRODUCT';
export const ADD_PRODUCT='ADD_PRODUCT';